### ISSUE TITLE
运行swoole 怎么对docker运行中的容器加多端口映射？

### ISSUE THREAD

**Issue by Orocker** [garymengcom/dnmp#100]
你好，我安装了dnmp ，在php7.2容器运行swoole创建了一个tcp服务器，监听9501端口，
我在docker-compose.yml文件加了ports重新构建端口还是没有映射上。

```
  php72:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_XDEBUG: ${PHP72_XDEBUG}  
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    ports:
      - "${SWOOLE_TCP_PORT}:9501"
    networks:
      - default
```
请问怎么将宿主机的9501端口映射到容器内部呢？谢谢
@yeszao
